### ISSUE TITLE
gum file ignore the path in version 0.10.0

### ISSUE THREAD

**Issue by amitnoph** [charmbracelet/gum#326]
**Describe the bug**
gum file ignores the path parameter

**To Reproduce**
1. running on rhel 8.4, with gum version 0.10.0
2. use ```gum file <some path>``` 

**Expected behavior**
expected the initial selection will start from ```<some path>```
instead it starts from current dir

**Comment by maaslalani** [comment]
Thanks so much for creating this issue. Should be fixed by #327

**Comment by licht1stein** [comment]
@maaslalani it's still a problem in the brew version, how can I update?

**Comment by maaslalani** [comment]
@licht1stein If you have go installed you can do:

```
go install github.com/charmbracelet/gum@main
```

You'll need to make sure that `GOBIN` is in your `PATH` as well.

https://stackoverflow.com/a/24070046

**Comment by licht1stein** [comment]
Thanks!
